Added option to check current package version
facundobatista/pyempaq pull request #28
Opened 2022-03-05 19:07 UTC by shivamshan

This PR makes the following changes:-

- adds command line option to check current python version
- black formatted pyempaq/main.py

## Code Proof
```
>>pyempaq -V
pyempaq 0.2.2

>>pyempaq --version
pyempaq 0.2.2
```

Signed-off-by: Shivam Shandilya <shivam.stpaulsdarjeeling@gmail.com>

2022-03-08 02:49 UTC, shivamshan commented on pyempaq/main.py
> +import pkg_resources
importing pkg_resources module that will fetch the version

2022-03-08 02:49 UTC, shivamshan commented on pyempaq/main.py
> +        help="The source file (pyempaq.yaml) or the directory where to find it.",
formatted by running black

2022-03-08 02:50 UTC, shivamshan commented on pyempaq/main.py
> +        )
formatted by black

2022-03-08 02:50 UTC, shivamshan commented on pyempaq/main.py
> +    )
formatted by black

2022-03-08 02:51 UTC, shivamshan commented on pyempaq/main.py
> +    )
added **--version** and **-V** option that will print the version of the module and exit

2022-03-19 12:16 UTC, facundobatista requested changes
Hello! Thanks for this! I annotated a detail inside.

Beyond that, though, this general request: do not run black on the project, thanks!

2022-03-19 12:16 UTC, facundobatista commented on pyempaq/main.py
> +        version=f"%(prog)s {pkg_resources.get_distribution('pyempaq').version}",
While this works when `pyempaq` is installed, it doesn't if you run it from the sources like `python -m pyempaq`. It needs to cover that case.

Also, please use a separate TESTED function. Thanks!

2023-02-06 00:14 UTC, facundobatista commented
Done n #25.

2023-02-06 00:14 UTC, closed without merging