Python's Logging in main
facundobatista/pyempaq pull request #30
Opened 2022-03-25 15:25 UTC by cacrespo

closes #7

2022-03-25 22:39 UTC, cacrespo commented
@facundobatista abordé #7 y #8 juntos porque necesitaba de `logging` en ambos. Si te parece mejor creo dos PRs

2022-04-04 18:41 UTC, facundobatista requested changes
Maravilloso, gracias por este laburo!! Ahí anoté unos detalles simples de corregir. Avisame si se te complica y lo corrijo yo directamente. 

Gracias de nuevo!

2022-04-04 18:41 UTC, facundobatista commented on pyempaq/main.py
> +#formatting logging
dejar un espacio luego del `#`

2022-04-04 18:41 UTC, facundobatista commented on pyempaq/main.py
> +                    datefmt='%I:%M:%S')
un mejor formato:
```
logging.basicConfig(format='%(asctime)s.%(msecs)03d %(levelname)-5s %(message)s', datefmt='%H:%M:%S')
```

porque...:
- muestra tres dígitos para los milisegundos, en el tuyo sobran dos ceros
- no separa con `|`, con espacios es suficiente
- le puse un `-5` al levelname, para que siempre tome 5 espacios (alineado a la izquierda), para que cuando arranca el mensaje siempre arranque en la misma columna
- la hora en el timestamp es "formato 24", no "12 am/pm"

2022-04-04 18:41 UTC, facundobatista commented on pyempaq/main.py
> +    if not args.loglevel is None:
cuando se usa el `is` se recomienda negarlo directamente, por legibilidad: `if args.loglevel is not None`

2022-04-04 18:58 UTC, cacrespo commented
@facundobatista Listo los cambios! A ver ahora qué tal...

2022-04-07 18:02 UTC, merged