add test for function find_venv_bin
facundobatista/pyempaq pull request #36
Opened 2022-04-13 17:55 UTC by cacrespo

Sigo con #10 y añado test pendiente.
Chequea que la función retorne un `Path` con el nombre del archivo correcto según SO.

@marcorichetta esto es lo que te comentaba.

2022-04-15 12:05 UTC, facundobatista requested changes
Buen arranque! Gracias! Ahí anoté un par de detalles, gracias!

2022-04-15 12:05 UTC, facundobatista commented on tests/test_common.py
> +    tmpdir = Path(tempfile.mkdtemp())
Hay un [fixture](https://docs.pytest.org/en/6.2.x/fixture.html) en `pytest` que te da un directorio temporal.... directamente hacé que la función reciba `tmp_path` y usala.

2022-04-15 12:05 UTC, facundobatista commented on tests/test_common.py
> +    # windows enviroment
Este sería un segundo test.

Y falta un tercero para el caso de que no se encuentren ninguno de los dos.

2022-04-15 12:05 UTC, facundobatista commented on tests/test_common.py
> +    shutil.rmtree(l_dir)  # for ignore linux env
Este `rmtree` no haría falta si usás el fixture que te indiqué arriba.

2022-04-16 18:26 UTC, cacrespo commented on tests/test_common.py
> +    tmpdir = Path(tempfile.mkdtemp())
Bárbaro! Lo apliqué para todos los tests.

2022-04-16 18:28 UTC, cacrespo commented on tests/test_common.py
> +    # windows enviroment
Indagando en la documentación que me pasaste llegué a `pytest.raises()` que entiendo es lo que se tiene que aplicar a ese último test.

2022-04-17 23:50 UTC, facundobatista commented on tests/test_common.py
> +    # windows enviroment
Eso! Bien!

2022-04-17 23:51 UTC, facundobatista approved these changes
Buenísimo, gracias!

2022-04-17 23:51 UTC, merged