moves logged_exec from main.py to common.py
facundobatista/pyempaq pull request #40
Opened 2022-04-19 16:04 UTC by cacrespo

#11 
Además de la función `logged_exec()` moví la clase `ExecutionError` porque si la quiero importar desde `common.py` explota por la referencia circular (main --> common --> main ...).

Entiendo que el formateo del logger ya queda establecido al principio de [main.py](https://github.com/cacrespo/pyempaq/blob/refactor_logged_exec/pyempaq/main.py#L24-L25). Es decir cuando lo traigo desde [common.py](https://github.com/cacrespo/pyempaq/blob/refactor_logged_exec/pyempaq/common.py#L11) no es necesario volver a setear eso ¿cierto?

Por último, en relación al test debería chequear tres situaciones:
- se ejecutó un comando cualquiera y fue todo OK.
- se ejecutó un comando y lanzó error
- se ejecutó un comando y se quedó esperando una respuesta (y lo tomamos como un error)

¿es así?

2022-04-24 19:58 UTC, cacrespo commented
Va el intento de tests.

Me da la impresión que estoy mezclando validar el resultado de la función junto a los mensajes que se generan. Lo veo como dos cosas distintas pero que pertenecen al mismo "'ambito" y deduzco que tienen que evaluarse en conjunto. 

`test_logged_exec_wait()` me costó bastante porque no termino de darme cuenta cómo replicar un parámetro para la función que haga que [`retcode` no sea `None`](https://github.com/cacrespo/pyempaq/blob/refactor_logged_exec/pyempaq/common.py#L47-L48). En los tests integrados del repositorio veo que para mac no funciona (debe ser que no existe el comando `dir` :facepalm: ).

Intenté vía `patch` generar el `retcode` del comando que se recibe dentro de la función pero sin éxito. Por otro lado, si hago eso en realidad no estaría testeando la función porque me armo el resultado a medida :stuck_out_tongue:

2022-04-25 13:10 UTC, cacrespo commented
closes #11 
Ready for review

2022-05-20 01:09 UTC, facundobatista requested changes
Hola! 

Estoy de acuerdo con todo el PR, gran laburo, gracias! Pero cambiaría las bibliotecas usadas... mirá:

- en vez de `caplog` usá [logassert](https://pypi.org/project/logassert/), es mil veces más piola para chequear logs
- para lo que es verificar llamadas a procesos, usá [pytest-subprocess](https://pypi.org/project/pytest-subprocess/)... no lo conocía hasta hace un par de días, pero parece muy interesante y justo lo que uno necesita...


Avisame si se complica con alguno de los dos y vemos... gracias!!!

2022-06-06 14:47 UTC, cacrespo commented
Hola! :wave: 
- reemplacé `caplog` por `loggasert`. No estoy seguro si es prolijo mantener estás dos lineas en `test_logged_exec()`:
```
    assert 'test' in logs.debug
    assert Exact("Executing external command: ['echo', 'test']") in logs.debug
```
¿por qué no dejar una sola y ya? (dejé las dos porque en los logs recuerdo que se registran ambas cosas en distintas entradas -o eso es lo que creo :P -). 
- en `test_logged_exec_error()` no me quedaba muy claro cómo hacer para generar el crash en el contesto del test así que se me ocurrió simplemente ejecutar un comando sin registrar en `pytest-process`.

Quedo atento a cualquier otro ajuste,

2022-06-13 22:07 UTC, facundobatista commented on tests/test_common.py
> +    assert 'test' in logs.debug
sí, como decís, esta linea puede volar

2022-06-13 22:08 UTC, facundobatista commented on tests/test_common.py
> +    logged_exec(['echo', 'test'])
no estás validando el resultado de esta ejecución... `logged_exec` devuelve el stdout del proceso, tenés que validar que eso funcione...

2022-06-13 22:09 UTC, facundobatista commented on requirements-dev.txt
> +pytest-subprocess
Al final esto no lo usaste, o me parece...?

2022-06-14 00:12 UTC, cacrespo commented on requirements-dev.txt
> +pytest-subprocess
Sí sí lo usamos... no es necesario hacer un import. 
Aplica cuando en los últimos dos tests le paso `fp` de parámetro.

2022-06-14 19:51 UTC, facundobatista commented on tests/test_common.py
> +    logged_exec(['echo', 'test'])
Esa linea sólo valida que algo esté en "los logs como debug", y lo que hay que probar es lo que devuelve la función...

2022-06-14 19:52 UTC, facundobatista commented on requirements-dev.txt
> +pytest-subprocess
ah, que oscuro.... podés usar `fake_process` en vez de `fp`, no? si sí, hacelo por favor, así queda más claro.. gracias!

2022-06-14 21:02 UTC, cacrespo commented on tests/test_common.py
> +    logged_exec(['echo', 'test'])
Ahh OK. Ahora sí! :smile: 

Mantuve los dos chequeos en la misma prueba:
- que se escriba en los logs lo que corresponde
- que la función retorne lo esperado

2022-06-19 15:15 UTC, facundobatista approved these changes
Buenísimo, gracias!!!

2022-06-19 15:15 UTC, merged