Logged exec in unpacker
facundobatista/pyempaq pull request #41
Opened 2022-06-12 22:10 UTC by cacrespo

#40 
Lo dejo en draft porque falla `test_unpacker()`. Todavía no sé muy bien dónde está el inconveniente.

2022-06-17 14:06 UTC, cacrespo commented
Me encontré con que a diferencia de `subprocess.run()` nuestro `logged_exec()` no imprimía por consola los distintos resultados. Lo intenté arreglar añadiendo `print()` [acá](https://github.com/facundobatista/pyempaq/pull/41/commits/08c048c00c56154636b90ed957e6287ca3360f76#diff-31d02246f74df2d772d59cd95881b6f1059532087f2bbf1043c60206f76f540dR47-R51)

Si bien pasa todos los tests identifiqué un comportamiento extraño cuando la aplicación a empaquetar contiene `input()`. Cuando se ejecuta el archivo .pyz espera que ingresemos los valores sin mostrar el texto y una vez que se ejecuta vuelca todo junto en pantalla. Puse un ejemplo simple que reproduce el error en examples/test_print.

Estoy medio perdido en este momento. Si se te ocurre una pista por dónde indagar bienvenido el feedback. 
Mientras tanto voy leyendo en profundidad la documentación sobre `subprocess`.

Saludos

2022-06-19 15:23 UTC, facundobatista commented
Hola! Creo que entiendo el problema. Me parece que la razón de todo es que el issue #12 no está bien especificado (mi error!).

Ahora revisando bien el `unpacker.py` veo que hacemos subprocess.run en dos lugares:

- al instalar las dependencias (en `main` sería la linea 112)
- al correr el "comando final", dentro de `run_command`, linea 68.

El `subprocess.run` que tenemos que reemplazar por `logged_exec` es aquel donde realizamos una operatoria interna, en donde instalamos las dependencias. La idea atrás de esto es no "leakear a pantalla" todas esas lineas a menos que se ejecute en debug o algo.

Por otro lado, la ejecución del "comando final" NO tiene que reemplazarse por el logged_exec, tenemos que conservar esa ejecución "lo más pura posible", o en otras palabras "entrometiéndonos lo menos posible".

Creo que con esto queda aclarado, si no avisame!! Gracias, saludos!

2022-06-20 14:45 UTC, cacrespo commented
Super claro y ahora me hace más sentido todo el código! :smile:
Va de nuevo con los ajustes.
Saludos

2022-06-20 18:45 UTC, facundobatista requested changes
+1, pero hay un cambio a deshacer. Gracias!!

2022-06-20 18:45 UTC, facundobatista commented on pyempaq/common.py
> +            universal_newlines=True)
Deshacé este cambio que es sólo estético (y no es para fixear flake8, digamos)

2022-06-20 19:20 UTC, facundobatista approved these changes
Genial!!

2022-06-20 19:21 UTC, facundobatista commented
Graciasssssssss!

2022-06-20 19:21 UTC, merged